### PR TITLE
Use own $ variable, make sure Jquery can be loaded

### PR DESCRIPTION
**Pull request by dollars0427**
If use $ variable directly, Wookmark may be cannot call Jquery function (Such as running on Drupal).

### CODE REVIEW

**Comment by yookoala** [comment]
I have same issue using the library with Drupal. Drupal use jQuery with [noConflict mode](https://api.jquery.com/jquery.noconflict/) to avoid conflicting use of the `$` variable. Therefore jQuery plugin that uses `$` alias directly will have problem.

As changed by this PR, it is a common practice to use [immediately-invoked function expression](http://benalman.com/news/2010/11/immediately-invoked-function-expression/) to protect `$` alias in your scope. It is also cited in the [official learning doc](https://learn.jquery.com/plugins/basic-plugin-creation/#protecting-the-alias-and-adding-scope).

Hope this PR is accepted.

**Comment by Sebobo** [comment]
Hey, thanks for the PR!
Of course this has to be fixed, I overlooked that because I test on the existence of jQuery first. But I'm not sure if the closure is the best idea. 
Then the plugin looks more like a jQuery plugin which it actually isn't necessarily.
Instead the ~3 places where jQuery is used could just be changed to use jQuery instead of $.

What do you guys think?

**Comment by yookoala** [comment]
[Immediate-invoked function expression](http://benalman.com/news/2010/11/immediately-invoked-function-expression/) binds the `jQuery` variable when the script is called. Whereas if you changed all `$` to `jQuery`, the script will simply call the current window.jQuery object.

In that sense, immediate-invoked function is much more friendly to jQuery users when they need to use multiple jQuery versions together. They simply have to arrange the script call order properly like this:
```html
...
<script src="js/jquery-3.1.1.js" />
<script src="js/Wookmark.js" />
<script src="js/jquery-1.17.1.min.js" />
<script src="js/some-old-plugin.js" />
...
```

So as long as Wookmark is depending on jQuery, I think adopting the pattern is a better idea than replacing all `$` with `jQuery`.

**Comment by Sebobo** [comment]
@yookoala true, I never do that, but I know there are websites which need it. 
I'll try to make a new release in the next days.

**Comment by dollars0427** [comment]
@yookoala @Sebobo  Thank you very much! :)

**Pull request merged**
